### ISSUE TITLE
Jiggler asks for Accessibility to be on each time Mac starts

### ISSUE THREAD

**Issue by XRayAdamo** [bhaller/Jiggler#29] opened 2023-04-25 17:01 UTC
Jiggler asks for Accessibility to be on each time Mac starts. Even though it is already on. I do not know if this is Jiggler problem or current Mac os, but no other apps are asking the same question when mac starts.

What kind of info needed to fix it?

**Comment by bhaller** [comment] 2023-04-25 21:04
Well, I guess the first question is, are you actually granting it the permission it wants?  And if you open up System Preferences, are you seeing that that permission has indeed been granted, and that macOS remembers it?  Two other things occur to me: (1) might you have more than one copy of Jiggler on your machine, such that you granted permission to one copy of the app but you're actually running a different copy of the app; and (2) have you correctly installed Jiggler into your /Applications folder, or are you running it off of a disk image or something?  Oh, and (3) are you running the latest version of Jiggler?  That's all I can think of.  The accessibility permission stuff is totally out of Jiggler's control; if the problem is not user error in some way (such as the above ideas), then it sounds like a bug in Apple's code, and I would have no idea how to fix it.

**Comment by XRayAdamo** [comment] 2023-04-25 22:07
Here is my story. I did have use a different version, compiled it by myself. Then I decided to use the latest version as binary. I installed and run the new version and got thet permission request. I have removed all traces of Jiggler from settings and let the recent version ask permission again, but it didn't help.
I suppose installing new version (in a different location) broke something in MacOs.

**Comment by bhaller** [comment] 2023-04-25 22:28
That may be true.  There is presumably somewhere in preferences that you could wipe to make your system forget, and then it would work again.  Anyhow, this sounds like Apple's bug, and I don't think there's anything I can do about it, sorry.  My only idea is to try renaming Jiggler to, say, Jiggler1; maybe removing the identical name will work around the bug.  Anyhow, I'm going to close this issue since it's out of my control.  Good luck!

**Closed by bhaller** 2023-04-25 22:28 UTC

**Comment by XRayAdamo** [comment] 2023-04-25 22:30
Its okay. I will check what I can do with Mac to resolve this issue. You can close this bug report. Thank you
